server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: CMT+8
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433; DatabaseName=test
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
